CREATE TABLE IF NOT EXISTS Notifications (
    NotificationId SERIAL PRIMARY KEY,
    UserId INT NOT NULL,
    Message VARCHAR(500) NOT NULL,
    IsRead BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT FK_Notifications_Users FOREIGN KEY (UserId)
        REFERENCES Users(UserId) ON DELETE CASCADE
);
